version: '3'

services:
  first_container:
    build:
      ./cfg
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
        - ./sql:/docker-entrypoint-initdb.d